### ISSUE TITLE
关于信息门户的登录问题。

### ISSUE THREAD

**Issue by akawi-kkk** [Saafo/grades-spyer#1]
请问一下楼主有研究过不用selenium来登录吗？比如表单数据的js加密是怎么实现的？

**Comment by Saafo** [comment]
@akawi-kkk 去年研究过类似的问题，当时加密方式和密钥都写在js里，你打个断点调试调试应该能看到。（不知道最近一次升级改了没有，学校就是这方面经常改经常改，selenium写出来基本上不会受到改动的影响）不过当时调试的时候被信息中心打过电话，之后就没有再研究了。这次一个是想尽快做出来这次出成绩能用上，另一个也是在尽量模仿用户的正常行为让银杏服务器不要有太大压力。
